# Numpy Universial Functions
- add(x1, x2)
- subtract(x1, x2)
- numpy.sqrt
- exp
- log, log10, log2, log1p
- sin, cos, tan
- arcsin, arccos, arctan
- sinh, cosh, tanh
- floor, ceil
- round
- isnan, isfinite, isinf
- minimum, maximum
- add, subtract, multiply, divide, power
- greater, greater_equal, less, less_equal, equal, not_equal
- copysign
- nextafter
- logaddexp, logaddexp2
- fabs
- sign
- absolute

In [18]:
#1 add

import numpy as np

m_1 = np.arange(4).reshape(2,2)

m_2 = np.random.randint(0,10,(2,2))


display(np.add(m_1,m_2))
display(m_1 + m_2)

array([[ 6,  6],
       [ 5, 10]])

array([[ 6,  6],
       [ 5, 10]])

In [29]:
#2 subtract

m_1 = np.arange(4).reshape(2,2)

m_2 = np.random.randint(0,10,(2,2))
display(m_1)
display(m_2)

np.subtract(m_1,m_2)

array([[0, 1],
       [2, 3]])

array([[8, 5],
       [1, 6]])

array([[-8, -4],
       [ 1, -3]])

In [38]:
#3 sqrt  ... square root

m_2 = np.arange(3*3).reshape(3,3)

display(m_2)

display(np.sqrt(m_2))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [10]:
#4 exp

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2*np.pi, 2*np.pi, 100)
#display(x)

xx = x + 1j * x[:, np.newaxis] # a + ib over complex plane

out = np.exp(xx)
display(out)

array([[1.86744273e-03+4.57391553e-19j, 2.12018428e-03+5.19295378e-19j,
        2.40713211e-03+5.89577328e-19j, ...,
        4.15432121e+02+1.01751523e-13j, 4.71657115e+02+1.15522675e-13j,
        5.35491656e+02+1.31157628e-13j],
       [1.85241881e-03+2.36404157e-04j, 2.10312700e-03+2.68399330e-04j,
        2.38776629e-03+3.04724760e-04j, ...,
        4.12089892e+02+5.25905715e+01j, 4.67862545e+02+5.97082315e+01j,
        5.31183525e+02+6.77892025e+01j],
       [1.80758877e-03+4.69004483e-04j, 2.05222962e-03+5.32480014e-04j,
        2.32998040e-03+6.04546385e-04j, ...,
        4.02116982e+02+1.04334941e+02j, 4.56539892e+02+1.18455735e+02j,
        5.18328453e+02+1.34487651e+02j],
       ...,
       [1.80758877e-03-4.69004483e-04j, 2.05222962e-03-5.32480014e-04j,
        2.32998040e-03-6.04546385e-04j, ...,
        4.02116982e+02-1.04334941e+02j, 4.56539892e+02-1.18455735e+02j,
        5.18328453e+02-1.34487651e+02j],
       [1.85241881e-03-2.36404157e-04j, 2.10312700e-03-2.68399330e-0

In [ ]:
#5 log, log10, log2, log1p

In [ ]:
#6 sin, cos, tan


In [11]:
#7 arcsin, arccos, arctan


In [12]:
#8 sinh, cosh, tanh


In [13]:
#9 floor, ceil


In [15]:
#10 round


In [16]:
#11 isnan, isfinite, isinf


In [17]:
#12 minimum, maximum


In [18]:
#13 add, subtract, multiply, divide, power


In [19]:
#14 greater, greater_equal, less, less_equal, equal, not_equal


In [20]:
#15 copysign


In [21]:
#16 nextafter


In [22]:
#17 logaddexp, logaddexp2


In [23]:
#18 fabs


In [24]:
#19 sign


In [ ]:
#20 absolute