# Numpy Universial Functions
- add(x1, x2)
- subtract(x1, x2)
- numpy.sqrt
- exp
- log, log10, log2, log1p
- sin, cos, tan
- arcsin, arccos, arctan
- sinh, cosh, tanh
- floor, ceil
- round
- isnan, isfinite, isinf
- minimum, maximum
- add, subtract, multiply, divide, power
- greater, greater_equal, less, less_equal, equal, not_equal
- copysign
- nextafter
- logaddexp, logaddexp2
- fabs
- sign
- absolute

In [18]:
#1 add

import numpy as np

m_1 = np.arange(4).reshape(2,2)

m_2 = np.random.randint(0,10,(2,2))


display(np.add(m_1,m_2))
display(m_1 + m_2)

array([[ 6,  6],
       [ 5, 10]])

array([[ 6,  6],
       [ 5, 10]])

In [29]:
#2 subtract

m_1 = np.arange(4).reshape(2,2)

m_2 = np.random.randint(0,10,(2,2))
display(m_1)
display(m_2)

np.subtract(m_1,m_2)

array([[0, 1],
       [2, 3]])

array([[8, 5],
       [1, 6]])

array([[-8, -4],
       [ 1, -3]])

In [38]:
#3 sqrt  ... square root

m_2 = np.arange(3*3).reshape(3,3)

display(m_2)

display(np.sqrt(m_2))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [10]:
#4 exp

import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-2*np.pi, 2*np.pi, 100)
#display(x)

xx = x + 1j * x[:, np.newaxis] # a + ib over complex plane

out = np.exp(xx)
display(out)

array([[1.86744273e-03+4.57391553e-19j, 2.12018428e-03+5.19295378e-19j,
        2.40713211e-03+5.89577328e-19j, ...,
        4.15432121e+02+1.01751523e-13j, 4.71657115e+02+1.15522675e-13j,
        5.35491656e+02+1.31157628e-13j],
       [1.85241881e-03+2.36404157e-04j, 2.10312700e-03+2.68399330e-04j,
        2.38776629e-03+3.04724760e-04j, ...,
        4.12089892e+02+5.25905715e+01j, 4.67862545e+02+5.97082315e+01j,
        5.31183525e+02+6.77892025e+01j],
       [1.80758877e-03+4.69004483e-04j, 2.05222962e-03+5.32480014e-04j,
        2.32998040e-03+6.04546385e-04j, ...,
        4.02116982e+02+1.04334941e+02j, 4.56539892e+02+1.18455735e+02j,
        5.18328453e+02+1.34487651e+02j],
       ...,
       [1.80758877e-03-4.69004483e-04j, 2.05222962e-03-5.32480014e-04j,
        2.32998040e-03-6.04546385e-04j, ...,
        4.02116982e+02-1.04334941e+02j, 4.56539892e+02-1.18455735e+02j,
        5.18328453e+02-1.34487651e+02j],
       [1.85241881e-03-2.36404157e-04j, 2.10312700e-03-2.68399330e-0

In [5]:
#5 log, log10, log2, log1p
import numpy as np
np.log([1, np.e, np.e**2, 0])

np.log10([1e-15, -3.])

x = np.array([0, 1, 2, 2**4])
np.log2(x)

np.log1p(1e-99)
1e-99
np.log(1 + 1e-99)

/tmp/ipykernel_244397/3600734746.py:3: RuntimeWarning: divide by zero encountered in log
  np.log([1, np.e, np.e**2, 0])
/tmp/ipykernel_244397/3600734746.py:5: RuntimeWarning: invalid value encountered in log10
  np.log10([1e-15, -3.])
/tmp/ipykernel_244397/3600734746.py:8: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


0.0

In [10]:
#6 sin, cos, tan
np.sin(np.pi/2.)

display(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. ))

display(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. ))

display(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. ))

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [12]:
#7 arcsin, arccos, arctan
display(np.arcsin(1) )
display(np.arctan(1) )
display(np.arccos(1) )



1.5707963267948966

0.7853981633974483

0.0

In [14]:
#8 sinh, cosh, tanh

display(np.sinh(0))
display(np.sinh(np.pi*1j/2))
display(np.tanh(0))


0.0

1j

0.0

In [17]:
#9 floor, ceil

a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
display(np.floor(a))

display(np.ceil(a))


array([-2., -2., -1.,  0.,  1.,  1.,  2.])

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [25]:
#10 round

np.round(56294995342131.5,3)



56294995342131.51

In [30]:
#11 isnan, isfinite, isinf
#np.nan
#np.inf
np.isnan([np.log(-1.),1.,np.log(0)])

/tmp/ipykernel_244397/174175958.py:4: RuntimeWarning: invalid value encountered in log
  np.isnan([np.log(-1.),1.,np.log(0)])
/tmp/ipykernel_244397/174175958.py:4: RuntimeWarning: divide by zero encountered in log
  np.isnan([np.log(-1.),1.,np.log(0)])


array([ True, False, False])

In [33]:
#12 minimum, maximum
display(np.minimum([2, 3, 4], [1, 5, 2]))
display(np.maximum([2, 3, 4], [1, 5, 2]))

array([1, 3, 2])

array([2, 5, 4])

In [35]:
#13 add, subtract, multiply, divide, power





display(np.add(1.0, 4.0))
display(np.subtract(1.0, 4.0))
display(np.multiply(1.0, 4.0))
display(np.power(1.0, 4.0))
display(np.divide(1.0, 4.0))

5.0

-3.0

4.0

1.0

0.25

In [36]:
#14 greater, greater_equal, less, less_equal, equal, not_equal
display(np.greater([4,2],[2,2]))
display(np.greater_equal([4,2],[2,2]))
display(np.less([4,2],[2,2]))
display(np.less_equal([4,2],[2,2]))
display(np.equal([4,2],[2,2]))
display(np.not_equal([4,2],[2,2]))

array([ True, False])

array([ True,  True])

array([False, False])

array([False,  True])

array([False,  True])

array([ True, False])

In [37]:
#15 copysign
np.copysign(1.3, -1)

-1.3

In [38]:
#16 nextafter
np.nextafter(1.3, -1)

1.2999999999999998

In [42]:
#17 logaddexp, logaddexp2

prob1 = np.log(1e-50)
prob2 = np.log(2.5e-50)
prob12 = np.logaddexp(prob1, prob2)
display(prob12)

prob1 = np.log2(1e-50)
prob2 = np.log2(2.5e-50)
prob12 = np.logaddexp2(prob1, prob2)
prob1, prob2, prob12

-113.87649168120691

(-166.09640474436813, -164.77447664948076, -164.28904982231052)

In [45]:
#18 fabs

np.fabs(-12312312)

12312312.0

In [46]:
#19 sign

np.sign([-5., 4.5])


array([-1.,  1.])

In [47]:
#20 absolute

x = np.array([-1.2, 1.2])
np.absolute(x)

array([1.2, 1.2])